version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: brandnews-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - brandnews-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandnews-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      NEWS_API_KEY: ${NEWS_API_KEY}
      AIML_API_KEY: ${AIML_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - brandnews-net

volumes:
  mysql_data:

networks:
  brandnews-net:
